# Generated by Django 4.1.5 on 2023-01-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0002_contactcard_delete_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcard',
            name='dob',
        ),
        migrations.AddField(
            model_name='contactcard',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
