# Generated by Django 4.1.5 on 2023-01-21 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userhome', '0003_remove_contactcard_dob_contactcard_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcard',
            name='email',
        ),
        migrations.AddField(
            model_name='contactcard',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
