# Generated by Django 4.1.5 on 2023-01-21 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userhome', '0005_alter_contactcard_image_alter_contactcard_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
