# Generated by Django 4.1.5 on 2023-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0006_alter_contactcard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_model',
            name='age',
        ),
        migrations.AddField(
            model_name='registration_model',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
