# Generated by Django 4.1.5 on 2023-01-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0007_remove_registration_model_age_registration_model_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_model',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
