# Generated by Django 4.1.5 on 2023-01-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0008_alter_registration_model_dob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactCard',
        ),
    ]
